require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '15.1'

prepare_react_native_project!

target 'chatapp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath]
  )

  target 'chatappTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(installer, config[:reactNativePath])
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
